# site settings
title: code-nomade.github.io
subtitle: by Adolfo Andrés Hincapié Garcia  
email: bandreshin@gmail.com
description: A responsive site template designed by me<br /> and released under the Creative Commons.
baseurl: "/code-nomade.github.io" # the subpath of your site, e.g. /blog
url:
author: Adolfo Andrés Hincapié García
street_address: Patio Bonito
city: Medellín
state: An
zip_code: 55555
country: Colombia
phone: (57) 310 539 6184

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: http://code-nomade.github.io/
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
